services:

  booking:
    container_name: api-pizza-container
    image: pizza-app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5159:8080"
    volumes:
      - ./volumes/api/images:/app/images
    depends_on:
      - postgresql

  postgresql:
    container_name: api-postgresql-container
    image: postgres
    restart: on-failure
    ports:
        - "5432:5432"
    environment:
      POSTGRES_PASSWORD: saloDevDb1234
    volumes:
        - ./volumes/db:/var/lib/postgresql/data
